Fix Java compilation command (always use run.jar).

diff --git a/rbx/resources/packagers/boca/compile/java b/rbx/resources/packagers/boca/compile/java
--- a/rbx/resources/packagers/boca/compile/java
+++ b/rbx/resources/packagers/boca/compile/java
@@ -41,50 +41,50 @@
 
 umask 0022
 if [ "$1" == "" ]; then
-    echo "parameter problem"
-    exit 43
+  echo "parameter problem"
+  exit 43
 fi
 name="$1"
 if [ ! -r "$1" ]; then
-    echo "$1 not found or it's not readable"
-    exit 44
+  echo "$1 not found or it's not readable"
+  exit 44
 fi
 id -u bocajail >/dev/null 2>/dev/null
 if [ $? == 0 ]; then
-	bocau=`id -u bocajail`
-	bocag=`id -g bocajail`
-	chown bocajail.nogroup .
+  bocau=$(id -u bocajail)
+  bocag=$(id -g bocajail)
+  chown bocajail.nogroup .
 else
-	bocau=`id -u nobody`
-	bocag=`id -g nobody`
-	chown nobody.nogroup .
+  bocau=$(id -u nobody)
+  bocag=$(id -g nobody)
+  chown nobody.nogroup .
 fi
 if [ "$bocau" == "" -o "$bocag" == "" ]; then
-	echo "error finding user to run script"
-	exit 43
+  echo "error finding user to run script"
+  exit 43
 fi
 
 mkdir -p src
 if [ "${name##*.}" == "zip" -o "${name##*.}" == "ZIP" ]; then
-	unzip "$name" -d src
-    if [ "${name##*.}" == "zip" ]; then
-		name=`basename $name .zip`
-	else
-		name=`basename $name .ZIP`
-	fi
+  unzip "$name" -d src
+  if [ "${name##*.}" == "zip" ]; then
+    name=$(basename $name .zip)
+  else
+    name=$(basename $name .ZIP)
+  fi
 else
-	cp "$name" src
+  cp "$name" src
 fi
 chown -R $bocau src
 chmod -R 700 src
 
 # this script makes use of safeexec to execute the code with less privilegies
 # make sure that directories below are correct.
-sf=`which safeexec`
+sf=$(which safeexec)
 [ -x "$sf" ] || sf=/usr/bin/safeexec
 if [ ! -x $sf ]; then
-    echo "$sf not found or it's not executable"
-    exit 46
+  echo "$sf not found or it's not executable"
+  exit 46
 fi
 
 # setting up the timelimit according to the problem
@@ -98,31 +98,27 @@ time=30
 
 maxm=512
 if [ "$4" != "" -a "$4" -gt "512" ]; then
-maxm=$4
+  maxm=$4
 fi
 
-if [ "$2" == "" ]; then
-  jarfile=run.jar
-else
-  jarfile=$2
-fi
+jarfile=run.jar
 
-cdir=`pwd`
+cdir=$(pwd)
 echo "Current directory is $cdir" >&2
-mainname=`echo $name | cut -d'.' -f1`
+mainname=$(echo $name | cut -d'.' -f1)
 if [ "$mainname" == "" ]; then
   mainname=Main
 fi
 
-cat <<EOF > compileit.sh
+cat <<EOF >compileit.sh
 #!/bin/bash
-javac=`which javac`
+javac=$(which javac)
 [ -x "\$javac" ] || javac=/usr/bin/javac
 if [ ! -x \$javac ]; then
     echo "\$javac not found or it's not executable"
     exit 47
 fi
-jar=`which jar`
+jar=$(which jar)
 [ -x "\$jar" ] || jar=/usr/bin/jar
 if [ ! -x \$jar ]; then
     echo "\$jar not found or it's not executable"
@@ -146,8 +142,8 @@ chmod 755 compileit.sh
 
 echo $cdir | grep -q "/bocajail"
 if [ $? == 0 ]; then
-    cdir=`echo $cdir | sed "s/.*\/bocajail//"`
-    cat <<EOF > runit.sh
+  cdir=$(echo $cdir | sed "s/.*\/bocajail//")
+  cat <<EOF >runit.sh
 #!/bin/bash
 cd "$cdir"
 [ -f /proc/cpuinfo ] || /bin/mount -t proc proc /proc
@@ -162,33 +158,33 @@ if [ ! -d /bocajail ]; then
   /bin/umount /sys 2>/dev/null
 fi
 EOF
-    chmod 755 runit.sh
-    chroot /bocajail "$cdir/runit.sh"
-    if [ -r runit.retcode ]; then
-    	ret=`cat runit.retcode`
-    else
-		ret=99
-    fi
+  chmod 755 runit.sh
+  chroot /bocajail "$cdir/runit.sh"
+  if [ -r runit.retcode ]; then
+    ret=$(cat runit.retcode)
+  else
+    ret=99
+  fi
 else
-	echo "COMPILATION IS NOT BEING CHROOTED -- THIS IS NOT AN IDEAL SETTING"
-#	$javac "$name"
-	$sf -r1 -t$time -T$ttime -F256 -u256 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -d20000000 -m20000000 ./compileit.sh
-	ret=$?
+  echo "COMPILATION IS NOT BEING CHROOTED -- THIS IS NOT AN IDEAL SETTING"
+  #	$javac "$name"
+  $sf -r1 -t$time -T$ttime -F256 -u256 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -d20000000 -m20000000 ./compileit.sh
+  ret=$?
 fi
 if [ -f "stdout0" ]; then
-	cat "stdout0"
+  cat "stdout0"
 fi
 if [ -f "stderr0" ]; then
-	cat "stderr0"
+  cat "stderr0"
 fi
 rm -rf src/
 if [ "$ret" != "0" ]; then
-	echo "Compilation Error: $ret"
-	exit $ret
+  echo "Compilation Error: $ret"
+  exit $ret
 fi
-ret=`cat compileit.retcode`
+ret=$(cat compileit.retcode)
 if [ "$ret" != "0" ]; then
-	echo "Compilation Error: $ret"
-	ret=1
+  echo "Compilation Error: $ret"
+  ret=1
 fi
 exit $ret
