Add new runit script that supports tracking only solutions resource usage.

diff --git a/rbx/resources/packagers/boca/compile/kt b/rbx/resources/packagers/boca/compile/kt
--- a/rbx/resources/packagers/boca/compile/kt
+++ b/rbx/resources/packagers/boca/compile/kt
@@ -41,22 +41,22 @@
 
 umask 0022
 if [ "$1" == "" ]; then
-    echo "parameter problem"
-    exit 43
+	echo "parameter problem"
+	exit 43
 fi
 name="$1"
 if [ ! -r "$1" ]; then
-    echo "$1 not found or it's not readable"
-    exit 44
+	echo "$1 not found or it's not readable"
+	exit 44
 fi
 id -u bocajail >/dev/null 2>/dev/null
 if [ $? == 0 ]; then
-	bocau=`id -u bocajail`
-	bocag=`id -g bocajail`
+	bocau=$(id -u bocajail)
+	bocag=$(id -g bocajail)
 	chown bocajail.nogroup .
 else
-	bocau=`id -u nobody`
-	bocag=`id -g nobody`
+	bocau=$(id -u nobody)
+	bocag=$(id -g nobody)
 	chown nobody.nogroup .
 fi
 if [ "$bocau" == "" -o "$bocag" == "" ]; then
@@ -67,10 +67,10 @@ fi
 mkdir -p src
 if [ "${name##*.}" == "zip" -a "${name##*.}" == "ZIP" ]; then
 	unzip "$name" -d src
-    if [ "${name##*.}" == "zip" ]; then
-		name=`basename $name .zip`
+	if [ "${name##*.}" == "zip" ]; then
+		name=$(basename $name .zip)
 	else
-		name=`basename $name .ZIP`
+		name=$(basename $name .ZIP)
 	fi
 else
 	cp "$name" src
@@ -80,42 +80,38 @@ chmod -R 700 src
 
 # this script makes use of safeexec to execute the code with less privilegies
 # make sure that directories below are correct.
-sf=`which safeexec`
+sf=$(which safeexec)
 [ -x "$sf" ] || sf=/usr/bin/safeexec
 if [ ! -x $sf ]; then
-    echo "$sf not found or it's not executable"
-    exit 46
+	echo "$sf not found or it's not executable"
+	exit 46
 fi
 
 # setting up the timelimit according to the problem
-if [ "$3" == "" ]; then
-  time=5
-else
-  time=$3
-fi
-let "ttime = $time + 30"
+time=30
+ttime=30
 
 maxm=1024
 if [ "$4" != "" -a "$4" -gt "1024" ]; then
-maxm=$4
+	maxm=$4
 fi
 
 maxms=100
 
 if [ "$2" == "" ]; then
-  jarfile=run.jar
+	jarfile=run.jar
 else
-  jarfile=$2
+	jarfile=$2
 fi
 
-cdir=`pwd`
+cdir=$(pwd)
 echo "Current directory is $cdir" >&2
-mainname=`echo $name | cut -d'.' -f1`
+mainname=$(echo $name | cut -d'.' -f1)
 if [ "$mainname" == "" ]; then
-  mainname=Main
+	mainname=Main
 fi
 
-cat <<EOF > compileit.sh
+cat <<EOF >compileit.sh
 #!/bin/bash
 kotlinc=/snap/kotlin/24/bin/kotlinc
 [ -x "\$kotlinc" ] || kotlinc=/snap/bin/kotlinc
@@ -147,7 +143,7 @@ if [ "$ret" != "0" ]; then
 	echo "Compilation Error: $ret"
 	exit $ret
 fi
-ret=`cat compileit.retcode`
+ret=$(cat compileit.retcode)
 if [ "$ret" != "0" ]; then
 	echo "Compilation Error: $ret"
 	ret=1
diff --git a/rbx/resources/packagers/boca/interactive/cpp b/rbx/resources/packagers/boca/interactive/cpp
--- a/rbx/resources/packagers/boca/interactive/cpp
+++ b/rbx/resources/packagers/boca/interactive/cpp
@@ -61,6 +61,10 @@ fi
 # make sure that directories below are correct.
 sf=$(which safeexec)
 [ -x "$sf" ] || sf=/usr/bin/safeexec
+if [ -x "../safeexec.exe" ]; then
+  cp "../safeexec.exe" "safeexec.exe"
+  sf="./safeexec.exe"
+fi
 
 if [ "$1" == "" -o "$2" == "" -o "$3" == "" ]; then
   echo "parameter problem"
@@ -80,8 +84,9 @@ if [ ! -x "$sf" ]; then
 fi
 
 time=$3
-if [ "$time" -gt "0" ]; then
-  let "ttime = $time * 4"
+rtime=$(awk "BEGIN {print int($time+0.9999999)}")
+if [ "$rtime" -gt "0" ]; then
+  let "ttime = $rtime * 4"
 else
   time=1
   ttime=4
@@ -89,8 +94,8 @@ fi
 
 nruns=1
 if [ "$4" != "" ]; then
-  if [ "$4" -gt "0" ]; then
-    nruns=$4
+  if [ "$4" -gt "1" ]; then
+    echo "WARNING: nruns is set to $4, but it will be ignored because it's not supported by interactive problems"
   fi
 fi
 maxm=512000
@@ -134,7 +139,7 @@ if [ $? -eq 0 ]; then
   cd "$cdir"
   [ -f /proc/cpuinfo ] || /bin/mount -t proc proc /proc
   [ -d /sys/kernel ] || /bin/mount -t sysfs sysfs /sys
-  "$sf" -F10 -f$maxf -r$nruns -n0 -C. -U$bocau -G$bocag -d$maxm -m$maxm -t$time -T$ttime -ostdout0 -estderr0 -- ./runit.sh ./run.exe
+  ./runit.sh "$cdir" "$sf" "$ttime" -F10 -f$maxf -r$nruns -n0 -C. -U$bocau -G$bocag -d$maxm -m$maxm -t$time -T$ttime -- ./run.exe
   retval=\$?
   echo \$retval > runch.exitcode
   if [ ! -d /bocajail ]; then
@@ -153,12 +158,8 @@ EOF
     exit 49
   fi
 else
-  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-
-  "$sf" -F10 -f$maxf -r$nruns -n0 -C. -U$bocau -G$bocag -d$maxm -m$maxm -t$time -T$ttime -ostdout0 -estderr0 -- ./runit.sh ./run.exe
-  ret=$?
+  echo "ERROR: CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+  exit 48
 fi
 ### END OF BOCA RUN COMMAND
 
diff --git a/rbx/resources/packagers/boca/interactive/kt b/rbx/resources/packagers/boca/interactive/kt
--- a/rbx/resources/packagers/boca/interactive/kt
+++ b/rbx/resources/packagers/boca/interactive/kt
@@ -61,6 +61,10 @@ fi
 # make sure that directories below are correct.
 sf=$(which safeexec)
 [ -x "$sf" ] || sf=/usr/bin/safeexec
+if [ -x "../safeexec.exe" ]; then
+  cp "../safeexec.exe" "safeexec.exe"
+  sf="./safeexec.exe"
+fi
 
 if [ "$1" == "" -o "$2" == "" -o "$3" == "" ]; then
   echo "parameter problem"
@@ -90,8 +94,9 @@ if [ ! -x "$sf" ]; then
 fi
 
 time=$3
-if [ "$time" -gt "0" ]; then
-  let "ttime = $time * 4"
+rtime=$(awk "BEGIN {print int($time+0.9999999)}")
+if [ "$rtime" -gt "0" ]; then
+  let "ttime = $rtime * 4"
 else
   time=1
   ttime=4
@@ -99,8 +104,8 @@ fi
 
 nruns=1
 if [ "$4" != "" ]; then
-  if [ "$4" -gt "0" ]; then
-    nruns=$4
+  if [ "$4" -gt "1" ]; then
+    echo "WARNING: nruns is set to $4, but it will be ignored because it's not supported by interactive problems"
   fi
 fi
 maxm=512000
@@ -145,7 +150,7 @@ if [ $? -eq 0 ]; then
       exit 47
   fi
   export CLASSPATH=.:./run.jar:$CLASSPATH
-  "$sf" -r$nruns -t$time -T$ttime -istdin0 -F512 -u512 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -d40000000000 -m40000000000 -- "\$kotlin" -cp run.jar -J-Xmx${maxm}K -J-Xss${maxms}K -J-Xms${maxm}K "$name"
+  ./runit.sh "$cdir" "$sf" "$ttime" -r$nruns -t$time -T$ttime -F512 -u512 -U$bocau -G$bocag -n0 -C. -d40000000000 -m40000000000 -- "\$kotlin" -cp run.jar -J-Xmx${maxm}K -J-Xss${maxms}K -J-Xms${maxm}K "$name"
   retval=\$?
   echo \$retval > runch.exitcode
   if [ ! -d /bocajail ]; then
@@ -164,17 +169,8 @@ EOF
     exit 49
   fi
 else
-  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-  kotlin=$(which kotlin)
-  [ -x "$kotlin" ] || kotlin=/usr/bin/kotlin
-  if [ ! -x "$kotlin" ]; then
-    echo "$kotlin not found or it's not executable"
-    exit 47
-  fi
-  "$sf" -r$nruns -t$time -T$ttime -istdin0 -F512 -u512 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -d40000000000 -m40000000000 -- "$kotlin" -cp run.jar -J-Xmx${maxm}K -J-Xss${maxms}K -J-Xms${maxm}K "$name"
-  ret=$?
+  echo "ERROR: CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+  exit 48
 fi
 ### END OF BOCA RUN COMMAND
 
diff --git a/rbx/resources/packagers/boca/interactive/py3 b/rbx/resources/packagers/boca/interactive/py3
--- a/rbx/resources/packagers/boca/interactive/py3
+++ b/rbx/resources/packagers/boca/interactive/py3
@@ -61,6 +61,10 @@ fi
 # make sure that directories below are correct.
 sf=$(which safeexec)
 [ -x "$sf" ] || sf=/usr/bin/safeexec
+if [ -x "../safeexec.exe" ]; then
+  cp "../safeexec.exe" "safeexec.exe"
+  sf="./safeexec.exe"
+fi
 
 if [ "$1" == "" -o "$2" == "" -o "$3" == "" ]; then
   echo "parameter problem"
@@ -77,8 +81,9 @@ if [ ! -x "$sf" ]; then
 fi
 
 time=$3
-if [ "$time" -gt "0" ]; then
-  let "ttime = $time * 4"
+rtime=$(awk "BEGIN {print int($time+0.9999999)}")
+if [ "$rtime" -gt "0" ]; then
+  let "ttime = $rtime * 4"
 else
   time=1
   ttime=4
@@ -86,8 +91,8 @@ fi
 
 nruns=1
 if [ "$4" != "" ]; then
-  if [ "$4" -gt "0" ]; then
-    nruns=$4
+  if [ "$4" -gt "1" ]; then
+    echo "WARNING: nruns is set to $4, but it will be ignored because it's not supported by interactive problems"
   fi
 fi
 maxm=512000
@@ -131,7 +136,7 @@ if [ $? -eq 0 ]; then
       echo "\$python3 not found or it's not executable"
       exit 47
   fi
-  "$sf" -F256 -u256 -f$maxf -r$nruns -n0 -C. -U$bocau -G$bocag -d$maxm -m$maxm -t$time -T$ttime -ostdout0 -estderr0 -- ./runit.sh "\$python3" "$name"
+  ./runit.sh "$cdir" "$sf" "$ttime" -F256 -u256 -f$maxf -r$nruns -n0 -C. -U$bocau -G$bocag -d$maxm -m$maxm -t$time -T$ttime -- "\$python3" "$name"
   retval=\$?
   echo \$retval > runch.exitcode
   if [ ! -d /bocajail ]; then
@@ -150,17 +155,8 @@ EOF
     exit 49
   fi
 else
-  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-  python3=$(which python3)
-  [ -x "$python3" ] || python3=/usr/bin/python3
-  if [ ! -x "$python3" ]; then
-    echo "$python3 not found or it's not executable"
-    exit 47
-  fi
-  "$sf" -F256 -u256 -f$maxf -r$nruns -n0 -C. -U$bocau -G$bocag -d$maxm -m$maxm -t$time -T$ttime -ostdout0 -estderr0 -- ./runit.sh "$python3" "$name"
-  ret=$?
+  echo "ERROR: CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+  exit 48
 fi
 ### END OF BOCA RUN COMMAND
 
