fix: fix BOCA interactive run when code is not chrooted

diff --git a/rbx/resources/packagers/boca/interactive/kt b/rbx/resources/packagers/boca/interactive/kt
--- a/rbx/resources/packagers/boca/interactive/kt
+++ b/rbx/resources/packagers/boca/interactive/kt
@@ -177,8 +177,18 @@ EOF
     exit 49
   fi
 else
-  echo "ERROR: CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-  exit 48
+  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+  java=$(which java)
+  [ -x "$java" ] || java=/usr/bin/java
+  if [ ! -x "$java" ]; then
+    echo "$java not found or it's not executable"
+    exit 47
+  fi
+  ./runit.sh "$cdir" "$sf" "$ttime" -r$nruns -t$time -T$ttime -F256 -u256 -U$bocau -G$bocag -n0 -C. -f20000 -d20000000 -m20000000 -- "\$java" -cp run.jar -Xmx${maxm}K -Xss${maxms}K -Xms${maxm}K MainKt
+  ret=$?
+  rm -rf fifo.in fifo.out
 fi
 ### END OF BOCA RUN COMMAND
 
diff --git a/rbx/resources/packagers/boca/interactive/py3 b/rbx/resources/packagers/boca/interactive/py3
--- a/rbx/resources/packagers/boca/interactive/py3
+++ b/rbx/resources/packagers/boca/interactive/py3
@@ -155,8 +155,18 @@ EOF
     exit 49
   fi
 else
-  echo "ERROR: CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-  exit 48
+  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+  echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
+  python3=$(which {{rbxPython3}})
+  [ -x "$python3" ] || python3=/usr/bin/{{rbxPython3}}
+  if [ ! -x "$python3" ]; then
+    echo "$python3 not found or it's not executable"
+    exit 47
+  fi
+  ./runit.sh "$cdir" "$sf" "$ttime" -F256 -u256 -f$maxf -r$nruns -n0 -C. -U$bocau -G$bocag -d$maxm -m$maxm -t$time -T$ttime -- "\$python3" "$name"
+  ret=$?
+  rm -rf fifo.in fifo.out
 fi
 ### END OF BOCA RUN COMMAND
 
